name: base
channels:
  - conda-forge
dependencies:
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - Pillow
  - h5py
  - cudatoolkit=11.1
  - pip:
    - torch==1.8.0+cu111
    - torchvision==0.9.0+cu111
    - --find-links https://download.pytorch.org/whl/torch_stable.html

